name: counter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  auto_route: ^11.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.0
  auto_route_generator: ^10.4.0
  freezed: ^3.2.5
  json_serializable: ^6.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/